### PR TITLE
Revert NBench.Runner project back to MSBuild 14

### PR DESCRIPTION
**Pull request by heynickc**
Due to NuGet issues using the .NET CLI to build the project targeting .NET 4.5.2, reverting this project to the original MSBuild 14 .csproj version.

### CODE REVIEW

**Comment by heynickc** [comment]
@Aaronontheweb If this passes checks, it is ok to merge.  The difference with this revert is that I left the NuGet publish step to be done by the .NET CLI.  It only uses what's been built into the .nupkg, which is reverted by changes to the "CreateNuget" FAKE target, so I will force a push to MyGet nightly again once this is approved.

**Comment by Aaronontheweb** [comment]
@heynickc looks like there's still a CI failure here on the compilation side

**Comment by heynickc** [comment]
@Aaronontheweb Yea, this is because MSBuild 15 isn't installed on the build agent.  Since NBench.Runner is being built using the older .csproj format, MSBuild 14 (on the build agent) is also trying to build the dependency (NBench.csproj) with MSBuild 14, which isn't possible since NBench.csproj is in the new format.

Going to have to try a different route.  Maybe custom .nuspec that grabs the .dll instead of trying to build it.

**Comment by heynickc** [comment]
Closing, resolved via #188

**Pull request closed without merging**
