### PR TITLE
[WIP] port to .netcore

### PR DESCRIPTION
**Pull request by maxim-s**
draft solution for .netcore

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@maxim-s any reason for the compilation errors here?

**Comment by maxim-s** [comment]
@Aaronontheweb  looks like incorrect framework for Nbench.Tests, but I'll check

**Comment by Aaronontheweb** [comment]
@maxim-s heh, odd that it compiled on Mono with no problems but not on .NET full this time around :p

**Comment by Aaronontheweb** [comment]
We'll probably want to add a separate build step for running the .NET Core CLI build step specifically

**Comment by Aaronontheweb** [comment]
What build command needs to be executed to build this?

**Comment by maxim-s** [comment]
@Aaronontheweb I'll add dotnetcore build, when everything will work fine. Now 19 tests failed

**Comment by maxim-s** [comment]
@Aaronontheweb could you install dotnet core to TeamCity server? https://www.microsoft.com/net/download/core

**Comment by Aaronontheweb** [comment]
@maxim-s the .NET Core build tools are installed on the server already (DotNetty .NET Core builds are still able to run) - looks like it's the FAKE script that is causing trouble.

**Comment by Aaronontheweb** [comment]
@maxim-s we need to lower the version of .NET Standard we support. No one is using 1.6 right now, but if we supported 1.2 then we could still support virtually all of our current users **and** be used in .NET Core applications. Could we please retarget to that?

**Comment by maxim-s** [comment]
@Aaronontheweb sure

**Comment by alexvaluyskiy** [comment]
@maxim-s Have you tried to run unit tests? I ran it on my PC and it 17-20 failed tests

**Comment by maxim-s** [comment]
@alexvaluyskiy yes 3 racy specs, but branch is not up to date, i ll update on monday

**Comment by alexvaluyskiy** [comment]
@maxim-s It is weird. I can't run the tests on the new DotNet CLI rc3 tooling even for net45. I'm using the same code changes as you. But I got 17 errors like this
```
Error Message:
 System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Stack Trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at NBench.Sdk.Compiler.ReflectionDiscovery.<>c.<LoadAllTypeConfigurators>b__4_0(IEnumerable`1 types, Assembly assembly)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at NBench.Sdk.Compiler.ReflectionDiscovery.LoadAllTypeConfigurators()
   at NBench.Tests.Sdk.Compiler.ReflectionDiscoveryConfiguratorSpecs.ReflectionDiscoveryCanFindBestFittingConfiguratorViaReflection(Type measurementType, Type expectedConfigura
torType)
```

**Comment by maxim-s** [comment]
@alexvaluyskiy sure, also would be great to test when all changes will be published, I can do it but, I want to do it when CI will be ready, so now waiting for changes on build server. Anyway thank you Alex I'll check

**Comment by maxim-s** [comment]
should I update to netstandart 1.6 ?

**Comment by Aaronontheweb** [comment]
Implemented as part of https://github.com/petabridge/NBench/pull/164

**Pull request closed without merging**
