### PR TITLE
NBench v1.0.1 Production Release

### PR DESCRIPTION
**Pull request by Aaronontheweb**
#### v1.0.1 March March 29 2017

This release resolves an issue with the v1.0.0 NuGet release for NBench.Runner in which clients installing the package via `Install-Package NBench.Runner` were not getting the NBench.dll dependency for NBench.Runner.exe.  NBench.dll is now compiled into NBench.Runner.exe.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Doing some more manual testing with the latest nightlies first to ensure that everything has been done correctly before pressing the merge button

**Comment by heynickc** [comment]
@Aaronontheweb I tested the .NET 4.5 runner against the MyGet nightlies and while the runner does start up indicating that it compiled successfully, it does not execute tests successfully against `NBench.Tests.Performance`.  It's having issues discovering benchmarks.  It's unknown whether the fix for the NuGet package is the root cause or if this was introduced earlier in the .NET Core porting project.  Reverting `NBench.Runner.exe` from .NET Core to .NET Framework .csproj.

**Comment by heynickc** [comment]
Please see #186 "Revert NBench.Runner project back to MSBuild 14" which is WIP.  Project is updated, however need to update build.fsx to conditionally build with MSBuild for this project, while still building all the other projects using .NET CLI

**Comment by heynickc** [comment]
@Aaronontheweb I tested the nightly release and ran against a test benchmark suite and the package works correctly.

**Pull request merged**
