### PR TITLE
Update release notes for v1.0.0 and increment version numbers in .csproj

### PR DESCRIPTION
**Pull request by heynickc**
This PR updates REALEASE_NOTES.md for v1.0.0 release and increments `<VersionPrefix>` to 1.0.0 for NuGet-published projects.

### CODE REVIEW

**Comment by heynickc** [comment]
@Aaronontheweb revised and pushed recommended changes to RELEASE_NOTES.md.  They reflect the changes made in PR #169 which is yet to pass checks.

**Comment by heynickc** [comment]
Typo - need to add code block Markdown to RELEASE_NOTES.md line 11.

```
<ItemGroup>
    <DotNetCliToolReference Include="NBench.Runner.DotNetCli" Version="1.0.0" />
</ItemGroup>
```

**Comment by Aaronontheweb** [comment]
@heynickc does this change still need to be made?

**Comment by heynickc** [comment]
@Aaronontheweb Yes, the change did need to be made.  I just pushed it.  Thanks.

**Pull request merged**
